version: '3.8'
services:

  mantisbt:
    build: ./mantisbt
    ports:
      - "8989:80"
    links:
      - postgres
    restart: always

  postgres:
    image: postgres:11
    hostname: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  pgadmin:
    build: ./pgadmin
#    image: dpage/pgadmin4:5.3
    ports:
      - "80:80"
    links: 
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
#      - type: volume
#      source: ./pgadmin/pgadmin4.db
#      target: /var/lib/pgadmin/pgadmin4.db
#      volume:
#        nocopy: true
      - './pgadmin/pgadmin4.db:/var/lib/pgadmin/pgadmin4.db'