version: '3'
services:
  postgres:
    image: postgres:11
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  pgadmin:
    image: dpage/pgadmin4:5.3
    ports:
      - "80:80"
    links: 
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes: 
      - ./pgadmin:/var/lib/pgadmin