mantisbt:
  build: ./mantisbt
  ports:
    - "8989:80"
  links:
    - postgres
  restart: always
  volumes:
    - ./config:/var/www/html/config
    - ./custom:/var/www/html/custom

postgres:
  build: ./postgresql
  environment:
    - POSTGRES_USER=mantis
    - POSTGRES_PASSWORD=mantis
    - POSTGRES_DB=bugtracker
  restart: always
  volumes:
    - ./postgresql:/var/lib/postgresql
